### ISSUE TITLE
Security audit

### ISSUE THREAD

**Issue by bjarneo** [HemmeligOrg/Hemmelig.app#1]
Feel free to audit this application. Would be highly appreciated.

**Comment by bjarneo** [comment]
Finding

Was able to bypass the mimetype restrictions by simply changing the Content-Type form header to something else. Example from the payload:
```
------WebKitFormBoundaryEQSxdNw95ZSUWTwh
Content-Disposition: form-data; name="file"; filename="MyCompressedFile.zip"
Content-Type: application/evilzip 
```

**Comment by RainerZufahl** [comment]
Not sure if this is a big issue, but I did notice that when trying to view a password-protected secret, the password entered to unlock the secret is sent in clear text. This could be a possible attack vector for secrets with multiple views. Note that I'm not a security expert for MITM attacks ;)

**Comment by bjarneo** [comment]
@RainerZufahl, that is a fair point. Usually this is how passwords are handled by all kinds of applications. One could, however, of course hash the password before shipping it to the backend on creation. Not sure if the bcrypt library is possible to use in the frontend, but, could be looked into. Could of course use sha256 -> backend -> bcrypt -> redis. The salt could be the encryption key.

Of course, this scenario requires the server running the application to be breached (if not the server admin is the malicious one)

One other thought here is that if anyone has access to the server, they can inject logic in the frontend as well, such as keylogging. This means they can get the secret.

However, not an bad idea to implement hashing of the password, nevertheless.

**Comment by bjarneo** [comment]
Yeah, correct :) And, if you have an MITM attack, then you surely have other issues as well ;)
