### ISSUE TITLE
Database options

### ISSUE THREAD

**Issue by d-513** [HemmeligOrg/Hemmelig.app#102]
Currently it seems that redis is used. This isn't really great for permanent data storage and is an obstacle for selfhosters.
Wouldn't it be better to have SQLite or other database be used?

I can make a PR with SQLite support if desired.

**Comment by bjarneo** [comment]
Yeah, I mean redis is OK for its usage, but it is costly to use memory as storage.

I have an old branch with sqlite, but havent looked into it for a while.

Sure you can create a PR for this, but then it has to be created as an adapter so it works as redis do today.

**Comment by dada513** [comment]
Sure, I think I'm gonna use PrismaJS https://www.prisma.io since that allows access to a lot of different db types with the same code

**Comment by bjarneo** [comment]
@dada513 sounds reasonable to me 🥂

**Comment by Zulgrib** [comment]
Interested in having support for other database engines too: we have dedicated mariadb clusters we would like to leverage instead of using redis we do not master. 

How can we help? 
Did you progress @dada513?

**Comment by bjarneo** [comment]
@Zulgrib, incoming PR for the database setup now. Have a look at that and give me a suggestion for how we could solve it to work for all providers by Prisma.
