### ISSUE TITLE
Bug for sign in on mobile rendering

### ISSUE THREAD

**Issue by julianfelipe98** [HemmeligOrg/Hemmelig.app#105]
if you  set the mobile view , the sign up button overlay the sign in button, it looks like this
![image](https://user-images.githubusercontent.com/48846122/193129171-84294080-f79f-45b6-bd19-5a751e44456e.png)

**Comment by julianfelipe98** [comment]
if U are agree I would like to work with this

**Comment by bjarneo** [comment]
Thanks for reporting. Please do work on it :)

**Comment by julianfelipe98** [comment]
do U have any discord chanel for support ?

**Comment by bjarneo** [comment]
That is actually not a bad idea. Create one now https://discord.gg/zgK3tHjz

**Comment by casperklein** [comment]
Maybe related: on mobile the footer is cut off after "Terms & Conditions".

**Comment by bjarneo** [comment]
Fixed
