### ISSUE TITLE
Review the sign in process

### ISSUE THREAD

**Issue by bjarneo** [HemmeligOrg/Hemmelig.app#106]
One of the things that has to be solved is not saving the JWT in local storage. Change this to cookies. Also have to make it possible to blacklist tokens if you delete your account / sign out.

Here is the sign in flow that is the future of Hemmelig:
https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html

Follow security best practices: https://developer.mozilla.org/en-US/docs/web/api/document/cookie

**Comment by dada513** [comment]
maybe more practical to use sessions rather than JWT?

**Comment by bjarneo** [comment]
Will continue using JWT

**Comment by bjarneo** [comment]
Changed the behaviour to use cookies (with jwt): https://github.com/HemmeligOrg/Hemmelig.app/commit/3a50974717b4b5eb12eeb1a386f0c44b4f37af06
