### ISSUE TITLE
Leverage the redux state for sign in / out

### ISSUE THREAD

**Issue by bjarneo** [HemmeligOrg/Hemmelig.app#107]
Solve that the sign in and out will set and remove the token. Currently, this is done in the header, but if we like to sign out elsewhere as well we need to trigger the createToken in Redux.

**Comment by theonly1me** [comment]
@bjarneo can you please add more details on what the requirement is here?

**Comment by bjarneo** [comment]
@theonly1me added a comment now :)

**Comment by theonly1me** [comment]
@bjarneo can you please assign this to me?
