### ISSUE TITLE
Leverage the useForm everywhere

### ISSUE THREAD

**Issue by bjarneo** [HemmeligOrg/Hemmelig.app#118]
This is currently used for the account route. Makes it easier to create error messages based on the input fields.

```js
import { useForm } from '@mantine/form';
```
https://mantine.dev/form/use-form/
* Secret creation
* User creation
* Sign in

**Comment by najeebkp** [comment]
Hi @bjarneo  please assign me this task.

**Comment by bjarneo** [comment]
Awesome, thanks @najeebkp
