### ISSUE TITLE
Upgrade to latest create-react-app

### ISSUE THREAD

**Issue by bjarneo** [HemmeligOrg/Hemmelig.app#122]

**Comment by najeebkp** [comment]
@bjarneo  i can take this up if you can guide me.

**Comment by bjarneo** [comment]
@najeebkp I might put this on hold. Basically get react-scripts up to version 5. But it seems to be complications. Have a try if you want to. Let me know if it is not that straight forward.

**Comment by bjarneo** [comment]
Changed to vite
