### ISSUE TITLE
feature: add issue template

### ISSUE THREAD

**Issue by bhattabhi013** [HemmeligOrg/Hemmelig.app#134]
Add issue template in the project.

**Comment by bhattabhi013** [comment]
Please assign this issue to me.

**Comment by bjarneo** [comment]
How would an issue template look like?

**Comment by bhattabhi013** [comment]
I'm thinking of creating something like this: 
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/47862474/196669732-fc314f90-7677-40eb-8df7-5730aaaa1786.png">

**Comment by bjarneo** [comment]
Please do :)
