### ISSUE TITLE
Password not recognised  from password manager 

### ISSUE THREAD

**Issue by thorrrr** [HemmeligOrg/Hemmelig.app#144]
### Description

HI 
Signed up using a password manager and managed to sign in with the details.
When i tried on another device password not recognised ?
Went back to or original device refused also cannot see a reset button?????

### Screenshots

![image](https://user-images.githubusercontent.com/8170673/205481447-8350fdef-4503-4208-85e3-c4afa859f5f6.png)

**Comment by bjarneo** [comment]
Hi @thorrrr ,

Hm, that is indeed clearly a bug. Thanks for reporting.

Regarding the reset, it has not been implemented yet, but it is coming.

Not sure why you could not sign in on a different device as there is no restriction here? 

If you want to I can delete your account if it is the same as the screenshot, then you can recreate it.
