### ISSUE TITLE
[DOCS] SECRET_DISABLE_USERS vs SECRET_USER_DISABLE=true

### ISSUE THREAD

**Issue by ITSNOTSTUPIDIFITWORKS** [HemmeligOrg/Hemmelig.app#147]
### Description

In the README.md and in docker-compose.yml the environment variable SECRET_DISABLE_USERS is mentioned, but in reality SECRET_USER_DISABLE is the right setting.

### Screenshots

![image](https://user-images.githubusercontent.com/41785417/207439201-8d119610-c3db-4f40-a8eb-76b64c888d0a.png)

**Comment by bjarneo** [comment]
Love your username :smile:

Yes, there was a change in the naming. Will update this. Thanks :)

**Comment by bjarneo** [comment]
Did a quick test, and it should be SECRET_DISABLE_USERS. SECRET_USER_DISABLE is the old env variable, so I think you are running the latest versioned release which uses that one. I will do a new release to make the releases up to speed so you do not have to use daily, weekly or bleeding
