### ISSUE TITLE
[FEATURE] Require sign-up authorization

### ISSUE THREAD

**Issue by pcgeek86** [HemmeligOrg/Hemmelig.app#154]
### Description

I'd like to self-host Hemmelig, but I would only want authorized / logged-in users to be able to store secrets. I should be able to reject user sign-ups, so that only the individuals I explicitly allow to have accounts can use the service.

Anonymous users should not be allowed to utilize Hemmelig, unless they are a receiver of a secret link.

I don't want just anyone in the world to be able to store unauthorized / illegal data on my instance of Hemmelig.

Hope to see this added in the future - thanks for the free / open source software!

**Comment by bjarneo** [comment]
Hi, thanks for your feature request. We do have a similar issue here. For reference https://github.com/HemmeligOrg/Hemmelig.app/issues/94

**Comment by alexandreteles** [comment]
A possible solution would be to run [oauth-proxy](https://oauth2-proxy.github.io/oauth2-proxy/) in front of the sensitive endpoints.

**Comment by bjarneo** [comment]
@alexandreteles cool project, going to have a look at this for other use cases as well

**Comment by bjarneo** [comment]
@pcgeek86 

On the newest version you are now able to set Hemmelig to read only mode. By using this mode, all users including signed in users with the role `user` do not have access to create secrets what so ever.

However, the `admins` and the `creators` are able to do so.

All of this can be found for your admin user in version 5.3.0.

It is not possible to disable user registration without disabling sign in for all users yet, but that feature is coming.

**Comment by bjarneo** [comment]
Another fix: https://github.com/HemmeligOrg/Hemmelig.app/commit/5239cc4b658a4a4b6f8d33024db87d9bccac4c63

Now it is possible to disable user registration as well, so if you use that setting in combination with read only, and set your users to `creators`, then you are all set.
