### ISSUE TITLE
[FEATURE] ARM support

### ISSUE THREAD

**Issue by mxmeeple** [HemmeligOrg/Hemmelig.app#158]
### Description

It would be nice to support ARM architecture, for those running things like the RasPi
I believe this would be easy to do with the github workflow actions by just adding docker/setup-buildx-action, docker/setup-qemu-action and using the platform tag on docker build

### Additional information

Tested in a [fork](https://github.com/fenaren/Hemmelig.app/blob/main/.github/workflows/publish_manual.yaml)

**Comment by bjarneo** [comment]
Feel free to open a PR if you have something ready 😁

**Comment by mxmeeple** [comment]
(Sorry that was a mis-click, to close)
Linking to my PR #159

**Comment by bjarneo** [comment]
Thank you for your PR! 🚀

**Comment by bjarneo** [comment]
I did this change to reduce the size of the docker images: https://github.com/HemmeligOrg/Hemmelig.app/commit/9d0f91a212b953df54c8b3b753928d3dbc870824

which means for the ARM images you need to prepend the prefix arm- to use them

**Comment by bjarneo** [comment]
On a second though I might misunderstand how this works, so they could just be the same image. I have to read up on docker platforms 😅
