### ISSUE TITLE
can't sign in or sign up in self-hosted

### ISSUE THREAD

**Issue by sokoow** [HemmeligOrg/Hemmelig.app#161]
### Description

Hi, thanks for the cool project!

I'm trying to self-host and I keep getting:

```
authentication.js:4          Uncaught (in promise) TypeError: Failed to fetch
    at authentication.js:4:24
    at f (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.next (regeneratorRuntime.js:117:21)
    at n (asyncToGenerator.js:3:20)
    at c (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21:12
    at authentication.js:3:20
```

wthile signing in or signing up, am I missing some extra settings?

**Comment by bjarneo** [comment]
Hi, thanks 🙂

Now, what can be the issue here. What env vars do you use? We got one for enabling and disabling users, but it should be enabled by default.

**Comment by sokoow** [comment]
Yeah, I got SECRET_DISABLE_USERS set to false

**Comment by sokoow** [comment]
Seems like I'm experiencing a hang on POST to /api/authentication/signup - in logs I only see

```
{"level":30,"time":1677585033859,"pid":18,"hostname":"hemmelig-6694d47779-mhbkf","reqId":"req-5c","req":{"method":"GET","url":"/api/authentication/signup","hostname":"hemmelig.my.domain.com","remoteAddress":"10.32.0.1","remotePort":54138},"msg":"incoming request"}
```

nothing more. Seems like something here requires more verbose logs in order to tell what is it hangin on.

**Comment by bjarneo** [comment]
sokoow, I am on vacation for a few days, but will look into it later. Strange thing it hangs on signup, makes me wonder why.

**Comment by sokoow** [comment]
ok no worries, it can wait

**Comment by sokoow** [comment]
sure, I run it on kubernetes, behind traefik ingress controller, here are my vars:

here are my envs:

```
         - name: SECRET_REDIS_TLS
           value: "false"
         - name: SECRET_REDIS_HOST
           value: "redis1-master"
         - name: SECRET_FILE_SIZE
           value: "2048"
         - name: SECRET_DO_SPACES_ENDPOINT
           value: "http://minio-svc:9000"
         - name: SECRET_DO_SPACES_KEY
           value: "MINIO_KEY"
         - name: SECRET_DO_SPACES_SECRET
           value: "MINIO_PASS"
         - name: SECRET_DO_SPACES_BUCKET
           value: "hemmelig"
         - name: SECRET_DISABLE_USERS
           value: "false"
         - name: SECRET_HOST
           value: "hemmelig.mydomain.com"
         - name: SECRET_JWT_SECRET
           value: "secret"
```

fun fact: POST to /api/secret also hangs - so it must be my config causing this.

**Comment by sokoow** [comment]
ok, I got it - it was redis misbehaving on my side

I'd use more logging in order to catch these sort of problems ealier, but somehow managed to find it :D

**Comment by bjarneo** [comment]
Ahh. Yes. Great that you figured it out. It should complain if it does not have a connection, but, I will look into better logging. Thank you :)
