### ISSUE TITLE
[FEATURE] A flag that can Enable/Disable the button "Create New Secret" in the page of the Shared Secret

### ISSUE THREAD

**Issue by Deddinho23** [HemmeligOrg/Hemmelig.app#168]
### Description

When you receive the link of the secret after you open it, there is the option of create a new one.
![image](https://user-images.githubusercontent.com/48152430/228294862-72422f09-0a6c-4f11-a951-20ad6de734b6.png)
In our organization we are using Hosted Hemmelig for sharing credentials, but through some rules we have conceded the possibility of creating Secret only to some people, meanwhile the shared Secret it's accessible by everyone who receive it.

Adding a flag like an env variable for "hiding" this button would be nice in this type of circumstances

**Comment by bjarneo** [comment]
Hi, so awesome you use Hemmelig in your organization!

Seems like something we can fix. I will start looking into the user management issue we have where we can do things like this. I.e. set which users that are able to create secrets. Thanks for this issue :)

**Comment by bjarneo** [comment]
Hi, so awesome you use Hemmelig in your organization!

Seems like something we can fix. I will start looking into the user management issue we have where we can do things like this. I.e. set which users that are able to create secrets. Thanks for this issue :)

**Comment by bjarneo** [comment]
This is now solved. If you create an instance based on the new 5.1.0 tag with these details set, you can set hemmelig to read only mode by everyone except of the admin user. Currently, there are no support for more admins, but that part is coming. If you want to do a workaround here, you can open the database and set the user role for other users from "user" to "admin".

ENV vars
```
| `SECRET_ROOT_USER`            | Override this for the root account username                           | groot                |
| `SECRET_ROOT_PASSWORD`        | This is the root password, override it with your own password         | iamgroot             |
| `SECRET_ROOT_EMAIL`           | This is the root email, override it with your own email               | groot@hemmelig.app   |
```
