### ISSUE TITLE
Can not loggin in self host

### ISSUE THREAD

**Issue by obito26m** [HemmeligOrg/Hemmelig.app#178]
### Description

since the update to 5 I can no longer log in ? It shows only 4-5 green bars that move and that was 

it runs under synology nas in docker container 

my code looks like this

```
docker run -p 3510:3000 -d --name=hemmelig \
   -v /volume1/docker/hemmelig/uploads:/var/tmp/hemmelig/upload/files \
   -v /volume1/docker/hemmelig/db:/home/node/hemmelig/database/ \
   hemmeligapp/hemmelig
```

### Screenshots

<a href="https://ibb.co/n3T0Mcw"><img src="https://i.ibb.co/28w63tF/Bildschirmfoto-2023-04-10-um-20-51-12.png" alt="Bildschirmfoto-2023-04-10-um-20-51-12" border="0"></a>

**Comment by bjarneo** [comment]
@obito26m did you migrate from redis to sqlite? Meaning, did you transfer the data.

**Comment by obito26m** [comment]
I was first on redis but when I wanted to encrypt a file today I had to log in which did not work so I thought you do it all over again so I deleted the container the folders and so on and then recreated the container with the command from above but still the same can gladly give logs from portainer with

**Comment by bjarneo** [comment]
@obito26m 

Can you try this command instead? Seems to be missing the docker tag.

```bash
docker run -p 3510:3000 -d --name=hemmelig \
   -v /volume1/docker/hemmelig/uploads:/var/tmp/hemmelig/upload/files \
   -v /volume1/docker/hemmelig/db:/home/node/hemmelig/database/ \
   hemmeligapp/hemmelig:v5.3.0
```

**Comment by obito26m** [comment]
@bjarneo 

ok i test it he ld down right now

**Comment by obito26m** [comment]
can it be because I put everything behind synology proxy to access it with a domain that goes through port 443 to give only 443 and 80 free in the router ?

**Comment by bjarneo** [comment]
Have you tried it on localhost on your computer?

**Comment by obito26m** [comment]
unfortunately I can not test because I have a mac with apple cpu and there is the last 4.4.0

**Comment by obito26m** [comment]
with arm 4.4.0 nothing happens when creating an account or login

**Comment by bjarneo** [comment]
You are correct. It will not work on the apple cpu. I forgot we are not building the ARM images anymore due to a prisma bug we have to solve, but it should still be working on linux servers. Have tested it by running this command:

For the Hemmelig.app instance, this is how the docker container is started using ansible, which is not really huge difference if we look at what you are doing, except of the env vars, of course:
```
      - name: Start the Hemmelig.app container
        docker_container:
            name: hemmelig
            image: '{{hemmelig_docker_image}}'
            env:
                SECRET_MASTER_KEY: '{{SECRET_MASTER_KEY}}'
                SECRET_JWT_SECRET: '{{SECRET_JWT_SECRET}}'
                SECRET_ROOT_USER: 'bjarneo'
                SECRET_ROOT_PASSWORD: '{{SECRET_ROOT_PASSWORD}}'
                SECRET_ROOT_EMAIL: 'repl@ace.me'
                SECRET_REDIS_HOST: '0.0.0.0'
                SECRET_MAX_TEXT_SIZE: '20048'
                SECRET_HOST: 'hemmelig.app'
            ports:
                - '3000:3000'
            volumes:
                - '/home/hemmelig/userdata/:/var/tmp/hemmelig/upload/files'
                - '/home/hemmelig/database/:/home/node/hemmelig/database/'
            restart_policy: always
        tags: hemmelig

**Comment by obito26m** [comment]
ok still will not because I'll probably wait for new version have now adapted the code me one time withr direct connection so redit one time without so saw my code 

docker run -d --name hemmelig \
-p 3510:3000 \
-e SECRET_MASTER_KEY=key \
-e SECRET_HOST=hemmelig.app \
-e SECRET_ROOT_USER=admin \
-e SECRET_ROOT_PASSWORD=password \
-e SECRET_ROOT_EMAIL=mai \
-e SECRET_MAX_TEXT_SIZE=20048 \
-e SECRET_FORCED_LANGUAGE=de \
-v /volume1/docker/hem/up:/var/tmp/hemmelig/upload/files \
-v /volume1/docker/hem/db:/home/node/hemmelig/database \
hemmeligapp/hemmelig

**Comment by bjarneo** [comment]
@obito26m can you show me the logs when you try to start v5.4.3?

**Comment by obito26m** [comment]
`
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
55249/01/09 09:12PM 30 undefined | pid=19 hostname=testhemm reqId=req-1 req=[object Object] msg=incoming request 
(node:19) [FSTDEP012] FastifyDeprecation: Request#context property access is deprecated. Please use "Request#routeConfig" or "Request#routeSchema" instead for accessing Route settings. The "Request#context" will be removed in `fastify@5`.
55249/01/09 09:13PM 30 undefined | pid=19 hostname=testhemm reqId=req-1 res=[object Object] responseTime=76.94451904296875 msg=request completed 
55249/01/10 05:46AM 30 undefined | pid=19 hostname=testhemm reqId=req-2 req=[object Object] msg=incoming request 
55249/01/10 05:47AM 30 undefined | pid=19 hostname=testhemm reqId=req-2 res=[object Object] responseTime=3.931118965148926 msg=request completed 
55249/01/10 02:15PM 30 undefined | pid=19 hostname=testhemm reqId=req-3 req=[object Object] msg=incoming request 
55249/01/10 02:15PM 30 undefined | pid=19 hostname=testhemm reqId=req-3 res=[object Object] responseTime=4.957579016685486 msg=request completed 
55249/01/10 10:41PM 30 undefined | pid=19 hostname=testhemm reqId=req-4 req=[object Object] msg=incoming request 
55249/01/10 10:41PM 30 undefined | pid=19 hostname=testhemm reqId=req-4 res=[object Object] responseTime=6.852500081062317 msg=request completed 
55249/01/11 07:17AM 30 undefined | pid=19 hostname=testhemm reqId=req-5 req=[object Object] msg=incoming request 
55249/01/11 07:18AM 30 undefined | pid=19 hostname=testhemm reqId=req-5 res=[object Object] responseTime=21.051159024238586 msg=request completed 
55249/01/11 03:50PM 30 undefined | pid=19 hostname=testhemm reqId=req-6 req=[object Object] msg=incoming request 
55249/01/11 03:50PM 30 undefined | pid=19 hostname=testhemm reqId=req-6 res=[object Object] responseTime=3.2785580158233643 msg=request completed`


that comes with me at 5.4.3 therefore I have my horn container first time on 4.0.0 there I can log in and use everything

**Comment by bjarneo** [comment]
Hm, should be no issues here. Did you try to sign in with the SECRET_ROOT_USER?

**Comment by obito26m** [comment]
yes sure have both tried to create a new so and with admin acc login so I do not understand that that's why I just use the 4 version there is still everything no idea where ran is whether on synology or firewall or rervers proxy

**Comment by bjarneo** [comment]
To be honest, I really do not know what happens at your end. Do you have the correct read and write permissions set for the database volume?

**Comment by ccarpo** [comment]
Good Morning. I have a similar issue. 
I also selfhost on debian. I use 5.8.2

This is the log from the application after I login:

**Comment by ccarpo** [comment]
Thank you. That solved it for me.
I misinterpreted the variable description.



25.04.2023 09:28:21 bjarneo ***@***.***>:

**Comment by bjarneo** [comment]
I see. Then I should write a better description. Glad it solved it :)
