### ISSUE TITLE
[FEATURE] Option to disable "Create a new secret" button

### ISSUE THREAD

**Issue by akzkak** [HemmeligOrg/Hemmelig.app#195]
### Description

Options to hide both the "Convert text to base64" and/or "Create a new secret" buttons on a shared secret link. 

And a way to skip the whole "View the secret" button would be a welcome addition as well heh

### Screenshots

![alt text](https://i.imgur.com/T16DQ98.png)

**Comment by bjarneo** [comment]
Hello, @akzkak 

1. You can disable people from creating secrets from the settings page of the application
2. No, there will not be a "skip the whole view the secret button". The reason for this button is that if the secret opens instantly, it will be opened by social media when you share them (they crawl the url).

**Comment by akzkak** [comment]
1. Made my frontend private via reverse proxy and only backend /secret themself are public. My goal is to make it as simple for non tech savvy people to receive there secret. So no user accounts required or "unnecessary" stuff on the page.
2. Understandable.

Can close again if request is simply to obscure. sry

**Comment by bjarneo** [comment]
I understand what you mean. I will open the issue again, and see how Hemmelig will behave going forward. I am currently redesigning and changing the features a bit.
