### ISSUE TITLE
[FEATURE] No external ressources

### ISSUE THREAD

**Issue by casperklein** [HemmeligOrg/Hemmelig.app#199]
### Description

I noticed, that some fonts are downloaded from `rsms.me`. This does expose Hemmelig's URL to the external host, like in #196

I haven't checked that: What happens, when Hemmelig is used in local networks (without internet access) and the external downloads fails?

Is it possible, to bundle those external things in Hemmelig, so that there are no dependencies to 3rd party sites?

**Comment by bjarneo** [comment]
https://github.com/HemmeligOrg/Hemmelig.app/releases/tag/v5.11.3
