### ISSUE TITLE
Example setup not working

### ISSUE THREAD

**Issue by casperklein** [HemmeligOrg/Hemmelig.app#200]
### Description

https://github.com/HemmeligOrg/Hemmelig.app#self-hosting

```bash
mkdir -p data/hemmelig database
chown 1000:1000 data/hemmelig database

docker run -p 3000:3000 -d --name=hemmelig \
   -v ./data/hemmelig/:/var/tmp/hemmelig/upload/files \ # For the file uploads
   -v ./database/:/home/node/hemmelig/database/ \       # For the sqlite database
   hemmeligapp/hemmelig:v5.11.1
```

Based on the example above, when a client opens Hemmelig via `http://hemmelig.example.com:3000`, the first request succeed. All further requests are done via https instead of http and failing, e.g. `https://hemmelig.example.com:3000/assets/index-81bb60d7.js`

This was already mentioned [here](https://github.com/HemmeligOrg/Hemmelig.app/issues/183#issuecomment-1512707031).

This should be fixed, or stated in the example, that a reverse proxy is mandatory 👍

**Comment by bjarneo** [comment]
This is true. I am wondering if I should turn off those security headers so it does not force https. I think I am being to strict here. Really up to the enduser to define their behaviour.

**Comment by bjarneo** [comment]
Was not supposed to close this automatically

**Comment by bjarneo** [comment]
https://github.com/HemmeligOrg/Hemmelig.app/releases/tag/v5.11.2

**Comment by casperklein** [comment]
I can't confirm, that this fixes the issue. Turning HSTS off, doesn't seem to be enough. Still all requests after the first one, are tried via HTTPS.

In the browser console I see the following:

Content-Security-Policy: Upgrade of unsafe request 'http://192.168.0.5:3000/assets/index-c8a280b5.js' for usage with 'https'

In the first HTTP request, the following header is returned:

```
Content-Security-Policy
	font-src 'self' https://rsms.me/;script-src 'self' 'unsafe-inline';default-src 'self';base-uri 'self';block-all-mixed-content;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests
```

I think the `upgrade-insecure-requests` is responsible for the clients decision to upgrade the connection from HTTP to HTTPS.

**Comment by bjarneo** [comment]
Right. I was to quick on the gun here. Thanks.

ons. 23. aug. 2023, 00:06 skrev Casper ***@***.***>:

**Comment by bjarneo** [comment]
https://github.com/HemmeligOrg/Hemmelig.app/releases/tag/v5.11.3

**Comment by casperklein** [comment]
I can confirm it's working now 👍
