### ISSUE TITLE
Can't upload files, due to permission error

### ISSUE THREAD

**Issue by FuckingToasters** [HemmeligOrg/Hemmelig.app#215]
### Description

```
[Error: EACCES: permission denied, open '/var/tmp/hemmelig/upload/files/_BhAwnflzvx3x-F49mKxmUzD2-fDWV69.json'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/var/tmp/hemmelig/upload/files/_BhAwnflzvx3x-F49mKxmUzD2-fDWV69.json'

}

EACCES: permission denied, open '/var/tmp/hemmelig/upload/files/_BhAwnflzvx3x-F49mKxmUzD2-fDWV69.json'
2023/09/28 09:02PM 30 pid=19 hostname=hemmelig reqId=req-2l res={"statusCode":403} responseTime=10.205626487731934 msg=request completed
```

### Additional information

I tried `chmod 777 /var` which sadly did not solve it.

**Comment by bjarneo** [comment]
It is not a bug. It is wrong permissions on the filesystem.

**Comment by bjarneo** [comment]
Should be some troubleshooting at the end of the readme

**Comment by FuckingToasters** [comment]
> Should be some troubleshooting at the end of the readme

in username, should i add root (linux username) or Infinimonster (hemmling username)?

**Comment by bjarneo** [comment]
https://github.com/HemmeligOrg/Hemmelig.app/issues/183#issuecomment-1520390666

**Comment by FuckingToasters** [comment]
Hmm, i looked at the suggested solution, my scret host were set to files.domain.com.

I now updated it to domain.com and tried it again, without success

**Comment by FuckingToasters** [comment]
update: i added user: root which seem to have solved this issue, but caused a new one.
