### ISSUE TITLE
[OTHER] Change donwload files button text

### ISSUE THREAD

**Issue by FuckingToasters** [HemmeligOrg/Hemmelig.app#217]
### What would you like to share?

I'd like to know, where i can change the text from the download button for files from hemmelig_files to something different like "Download Files"

Regards,
FuckingToasters

**Comment by bjarneo** [comment]
If you are creating your own version of this application you can figure this out yourself. I am not tech support. I notice a trend with all your issues that it is more or less tech support questions. I do not mind answering, but, when it comes to things like this that people either can easily figure out themselves, or if they are forking this product, then I will not spend my time answering or solving this.

**Comment by FuckingToasters** [comment]
> If you are creating your own version of this application you can figure this out yourself. I am not tech support. I notice a trend with all your issues that it is more or less tech support questions. I do not mind answering, but, when it comes to things like this that people either can easily figure out themselves, or if they are forking this product, then I will not spend my time answering or solving this.

Well these are Questions a user might have, you are the creator of it so you should know where the things are xd. I looked at every file but couldn't find it.
