### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by art-n** [HemmeligOrg/Hemmelig.app#222]
### Description

After logged in as admin, got a 401 unauthorized from /api/account.

Account page keeps loading and can't edit any account settings.

Any idea ? Cheers!

**Comment by bjarneo** [comment]
@art-n Hi,

Can you access the sqlite database and verify your admin account is there as an admin, and, if you have set any restrictions in the settings page?

**Comment by art-n** [comment]
Hello @bjarneo,

I haven't changed any settings.

Here's the result of the user table :
`d9ca06ed-0ea6-4afa-85e3-a6995610175f|root|email_replaced|pass_replaced|admin|1`

Seems good right ?

**Comment by art-n** [comment]
Adding SECRET_HOST did the trick 🤦🏼‍♂️

Thank you for creating this app btw !

**Comment by bjarneo** [comment]
Awesome that you figured it out :)

Thank you!
