### ISSUE TITLE
Terms and Condition option is duplicated

### ISSUE THREAD

**Issue by m4-droid** [HemmeligOrg/Hemmelig.app#224]
### Description

Terms and condition option is duplicated in the collapsed menu in mobile view

### Screenshots

![Screenshot (8)](https://github.com/HemmeligOrg/Hemmelig.app/assets/101039217/c74e8f51-93fb-490a-929a-ff1aa7c5ad12)

### Additional information

How to Replicate the issue?
visit [hemmelig.app](https://hemmelig.app) on mobile device and open collapsed menu
![Screenshot (7)](https://github.com/HemmeligOrg/Hemmelig.app/assets/101039217/e0d5c456-e312-4e99-8204-593f5076a9c8)

**Comment by m4-droid** [comment]
Hey!
Can you please assign this issue to me?
this would be my first contribution

**Comment by bjarneo** [comment]
Hello. Thanks for reporting. I have assigned to you, so feel free to solve it if you'd like :)

**Comment by bjarneo** [comment]
Thank you @m4-droid 🎉

**Comment by bjarneo** [comment]
@m4-droid https://github.com/HemmeligOrg/Hemmelig.app/releases/tag/v5.13.3
