### ISSUE TITLE
Default lifetime reduces from 72hr to 4hr after reset

### ISSUE THREAD

**Issue by m4-droid** [HemmeligOrg/Hemmelig.app#227]
### Description

I am not sure if this is the desired behavior but whenever a new secret url is being created with 72hr(default) lifetime (not on [hemmelig.app](https://hemmelig.app)) and when you delete that url, default lifetime comes back to 4hr.

### Additional information

How to replicate?
create url with 72hr new TTL, then delete that url, default TTL comes back to 4hr

**Comment by m4-droid** [comment]
hey! @bjarneo 
If this is a valid issue, can you assign this to me?

**Comment by bjarneo** [comment]
Hi, sure. I will assign you. thanks :)
