### ISSUE TITLE
Top view of lifetime select component is hidden by message area

### ISSUE THREAD

**Issue by m4-droid** [HemmeligOrg/Hemmelig.app#229]
### Description

some part of lifetime select component is hidden by message area

### Screenshots

![Screenshot (9)](https://github.com/HemmeligOrg/Hemmelig.app/assets/101039217/4fbe26d3-2202-4173-8bb0-e1d218f67804)

**Comment by m4-droid** [comment]
Hi,
You can assign this to me, I am working on it.

**Comment by bjarneo** [comment]
Hi. Thank you. What browser are you using as this goes upwards and not downwards.

Assigned it to you.

**Comment by m4-droid** [comment]
I have checked on chrome and edge, if enough is there it opens at bottom else top
