### ISSUE TITLE
What does log in do?

### ISSUE THREAD

**Issue by bjarneo** [HemmeligOrg/Hemmelig.app#24]
Really, nothing yet. Just providing basic auth name / secret for later usage.

**Comment by RainerZufahl** [comment]
Is it possible to disable the user account functionality on the self-hosted version? Couldn't find any environment variables to do this.

**Comment by bjarneo** [comment]
@RainerZufahl, no, but I can do this today 🚀

**Comment by RainerZufahl** [comment]
Damn, you're blazing fast! There's no time pressure, but I'd love to see the feature!

**Comment by bjarneo** [comment]
It was all coincidence, I just opened my notification page on github 😅

**Comment by bjarneo** [comment]
I am in need of this feature myself as well

**Comment by bjarneo** [comment]
@RainerZufahl should be possible to turn off user creation by using this env var: `SECRET_USER_DISABLE`. It is currently only in the bleeding-edge docker image. Will create a release sooner than later.

**Comment by bjarneo** [comment]
This has been changed to be done in the admin settings page in version 5.1.0
