### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by bjarneo** [HemmeligOrg/Hemmelig.app#26]
Make it possible to brand the self-hosted version.

**Comment by Zulgrib** [comment]
Hello, 
Do you need help with this feature?
If yes, where should we start looking at and which method should we employ? (Do we use an override folder where values take priority? Do we add new constant to control colors and path to logo? )

**Comment by bjarneo** [comment]
@Zulgrib , sure, but we first have to fix the replacement of redis with the sqlite PR, so that one is blocking. I want to save the colors and what not to the DB, and the colors we will use css-variables on :root to replace the colors. Same will apply for the logo.

**Comment by bjarneo** [comment]
This will not be supported
