### ISSUE TITLE
It seems that the I18N for Simplified Chinese(zh-CN) is no longer working

### ISSUE THREAD

**Issue by nyable** [HemmeligOrg/Hemmelig.app#275]
### Description

Hello,
When I set the browser language to Simplified Chinese(zh-CN), it seems that both the official website and self-hosted version cannot display the translated content correctly.
The file directory is located at `/locales/zh-cn/translation.json`, but request  `/locales/zh-CN/translation.json` and `/locales/zh/translation.json`.
`404 NOT FOUND` appears, resulting in the inability to display translated content.
When I rename directory 'zh-cn' to 'zh' or 'zh-CN' in the development environment, I am able to display translation results.

### Screenshots

# official
![zh-cn](https://github.com/HemmeligOrg/Hemmelig.app/assets/29651926/f67cb268-0ba7-4202-b769-f56ad5a6706f)
# localhost: default
![3](https://github.com/HemmeligOrg/Hemmelig.app/assets/29651926/4e749eb7-c14e-4636-bd52-f0a7bb5138c9)
# localhost: after rename zh-cn to zh-CN or zh
![rename_zh-CN](https://github.com/HemmeligOrg/Hemmelig.app/assets/29651926/cb59db57-0b45-4d9a-9a55-b6886a808c92)

**Comment by bjarneo** [comment]
Thank you! Can you create a PR for this?
