### ISSUE TITLE
Cannot find package '@vitejs/plugin-react

### ISSUE THREAD

**Issue by obito26m** [HemmeligOrg/Hemmelig.app#285]
### Description

I have reinstalled and restarted it once but it doesn't seem to want or be able to load this config 

### Screenshots

<img width="1618" alt="SCR-20240311-mzds" src="https://github.com/HemmeligOrg/Hemmelig.app/assets/41232458/af1c9cc5-2e2f-4a19-99d6-ac9610d0178f">

### Additional information

The docker runs on synology new os and the project was created with tag lates

**Comment by bjarneo** [comment]
Thanks. Yes. On it. Use 5.19.13 until 5.19.15 is released.

**Comment by bjarneo** [comment]
Latest should work
