### ISSUE TITLE
Docker container marked as unhealthy as healthcheck fails

### ISSUE THREAD

**Issue by graphixillusion** [HemmeligOrg/Hemmelig.app#291]
### Description

As the title says the docker container is marked as unhealthy as the healthcheck's command is failing with this error:

wget: can't connect to remote host: Connection refused

Container seems to work anyway.

**Comment by bjarneo** [comment]
Thanks for reporting.

I do not have any issues testing the docker-compose directly. 
```
3adbc04fe9c4   hemmeligapp/hemmelig:v5.19.4   "docker-entrypoint.s…"   3 minutes ago   Up 2 minutes (healthy)   0.0.0.0:3000->3000/tcp   hemmeligapp-hemmelig-1
```

Do you have any issues with your host? This seems local until otherwise is proven.

Anyway, I am adding a commit to improve the docker-compose file. I will add any health checks directly to the Dockerfile.

**Comment by graphixillusion** [comment]
Even with the changed healthcheck's command i still get unhealthy/connection refused. If i use 127.0.0.1 instead of localhost it works. Any clue?

**Comment by bjarneo** [comment]
@graphixillusion 

Right. What OS? I know you can have some issues if there is something wrong with your docker network, but I do not remember what. I.e. try to use --network=host (which usually connects the docker host to the localhost.

**Comment by graphixillusion** [comment]
debian 12

**Comment by bjarneo** [comment]
I remember I had a similar issue years ago. You should look into the network part for docker :)
