### ISSUE TITLE
Button titles are cut off

### ISSUE THREAD

**Issue by ltguillaume** [HemmeligOrg/Hemmelig.app#301]
### Description

Button titles are cut off. It seems that the button width is fixed, instead of taking into account the content.

### Screenshots

![image](https://github.com/HemmeligOrg/Hemmelig.app/assets/4777345/80c0ca65-7c1a-4704-ade9-1fa3174e7870)

**Comment by bjarneo** [comment]
@ltguillaume 
not sure if this is valid anymore, but please do verify with the v6 release

**Comment by bjarneo** [comment]
Yeah, broke many things when it comes to translations. Considering letting AI fix what is missing, and then people can just update it if they want to.

**Comment by bjarneo** [comment]
Thank you for the feedback.

**Comment by bjarneo** [comment]
Awesome. Thanks for fixing. 

This one I have to look into! `account.secrets.no_secrets`

**Comment by bjarneo** [comment]
New release coming
