### ISSUE TITLE
[FEATURE] Always show formatting toolbar

### ISSUE THREAD

**Issue by ltguillaume** [HemmeligOrg/Hemmelig.app#302]
### Description

Currently, the formatting toolbar only shows when the user has selected some text. I don't really think this is intuitive, especially because the toolbar also contains a button to add an image. The consequence of this is that the user now has to select some text in order to access this button, after which the selected text _gets replaced completely_ by the inserted image.

I believe it would be best to always show this toolbar at the top of the input field, just like here on GitHub.

Additionally, tooltips for the buttons which describe their function would be nice.

**Comment by bjarneo** [comment]
Done. However, images are removed for now.
