### ISSUE TITLE
Unable to Find Default Admin Credentials After Docker Compose Installation

### ISSUE THREAD

**Issue by enough-jainil** [HemmeligOrg/Hemmelig.app#305]
### What would you like to share?

I have successfully installed the application using `docker-compose`, but I can't find the default admin user ID and password. I haven't changed anything in the `docker-compose` file. Could someone please tell me what the default admin credentials are?

**Comment by bjarneo** [comment]
If you read the docker compose file you will find it. If you read the readme, you will find it.
