### ISSUE TITLE
Add docker tags for major/minor/patch versions

### ISSUE THREAD

**Issue by Quadrubo** [HemmeligOrg/Hemmelig.app#315]
### Description

As of the point of writing this, `v5.19.26` is the latest Hemmelig version.
As I'm manually updating my images and not using something like "latest", I have to change the image tag every new release. It would be nice if I wouldn't have to do that for patch releases (minor releases too).

Currently these tags are provided:
- `v5.19.26` - Version 5.19.26
- `v5.19.25` - Version 5.19.25
- `v5.18.1` - Version 5.18.1
- `latest` - Version 5.19.26

### Desired Behavior

I would propose a tag system like this:
- `v5.19.26` - Version 5.19.26
- `v5.19.25` - Version 5.19.25
- `v5.19`    - Version 5.19.26
- `v5`       - Version 5.19.26
- `latest` - Version 5.19.26

This would allow pinning to specific version and allows the user to choose which semver types they are okay with auto updating.
I for example would have pinned to `v5` and would have automatically gotten the update to `v5.19.26`.
However I would not get updates to `v6` automatically which would be desired for me.

**Comment by bjarneo** [comment]
That is a great idea!

**Comment by bjarneo** [comment]
major version added: https://hub.docker.com/layers/hemmeligapp/hemmelig/v5/images/sha256-e0af24f864d3356e913bfa3c7d49a86b95cc9c37311cc35814060cfd00030157?context=explore
