### ISSUE TITLE
After login error Bummer! Not logged in

### ISSUE THREAD

**Issue by cschwarck** [HemmeligOrg/Hemmelig.app#322]
### Description

Following the steps outlined for setting up Hemmelig with docker-compose, I get an error after logging in:
Bummer!
Not logged in
I've tried changing the default user and password with no luck.

### Screenshots

![Hemmelig](https://github.com/user-attachments/assets/aa764442-fc35-4af3-bbb2-216e079f93be)

### Additional information

    image: hemmeligapp/hemmelig:v5.19.17

**Comment by qmatiaslopez** [comment]
After getting the same error, I found that the solution is to set the `SECRET_HOST` variable in the `docker-compose.yml` file to the URL/IP from which the web is accessed.

Example:
- `192.168.56.10` - If you enter the IP directly  
- `secret.lab.local` - If you enter from this domain

Replace the value with your specific case.

**Comment by bjarneo** [comment]
Thank you, both. Did you get your answer @cschwarck ?
