### ISSUE TITLE
Upload files to Hemmelig self-hosted instance

### ISSUE THREAD

**Issue by taha-adel** [HemmeligOrg/Hemmelig.app#334]
### What would you like to share?

I wonder if there is a way to upload files to Hemmelig self-hosted instance for automation purposes. I checked the Hemmelig CLI but it seems it doesn't have an option to upload files.

**Comment by bjarneo** [comment]
I forgot to respond.

No, but it is something that can be implemented. For now you must use the api directly. No docs for that either 😅
