### ISSUE TITLE
PWA install prompt

### ISSUE THREAD

**Issue by bjarneo** [HemmeligOrg/Hemmelig.app#4]
Add script to prompt the user if they want to add the app to their home screen.

**Comment by bjarneo** [comment]
https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen

**Comment by bjarneo** [comment]
Since we are using CRA: https://create-react-app.dev/docs/making-a-progressive-web-app/

**Comment by minku-singh** [comment]
Hey @bjarneo , can I work on this?

**Comment by bjarneo** [comment]
Sure thing :)

**Comment by theonly1me** [comment]
@bjarneo Is any help still needed with this issue? If that is the case, I can pick this up.

**Comment by bjarneo** [comment]
@theonly1me please do :)

**Comment by bjarneo** [comment]
Thank you, @theonly1me 🚀
