### ISSUE TITLE
Implement Redux

### ISSUE THREAD

**Issue by bjarneo** [HemmeligOrg/Hemmelig.app#40]
And handle cases such at this really bad hack: https://github.com/HemmeligOrg/Hemmelig.app/blob/main/src/client/helpers/state-emitter.js

State manager ftw. Might have a look at a different state manager for React as well. KISS.

**Comment by TaneliR** [comment]
I could try to do this 👌

**Comment by bjarneo** [comment]
@TaneliR awesome 🙂
