### ISSUE TITLE
NPM packages missing

### ISSUE THREAD

**Issue by luismanson** [HemmeligOrg/Hemmelig.app#89]
Hi, this has to be an issue on my end but I have no idea where the problem is. 
Im  about to try the DE branch with language detection, but had to mess a bit with missing packages, they are the same I had to install when running the first fork I created... 
This is what i'm installing to be able to run `npm run client-dev`: 

```
    "@emotion/cache": "^11.10.3",
    "@emotion/react": "^11.10.4,
    "webpack": "^4.46.0"

```
Any advice? 

EDIT: there was also this warning: `npm WARN @mantine/styles@5.2.0 requires a peer of @emotion/react@>=11.9.0 but none is installed. You must install peer dependencies yourself.`

**Comment by bjarneo** [comment]
Should be enough with npm install, really. What OS are you using? npm version?

**Comment by luismanson** [comment]
Im in OpenSuSe Tumbleweed

npm -v: 6.14.8 (manually installed, don't know )
npm17 -v 8.5.2v (from the distro)

**Comment by bjarneo** [comment]
Hm, strange. Here is how it works for me from a clean repo git pull (3x speed):
https://user-images.githubusercontent.com/1419214/189608308-95d82a6d-f56e-40bd-b265-a24be47e89a8.mp4

**Comment by luismanson** [comment]
hmm...This confirms it's an issue on my end, not sure how to fix it tough. I think I'll just use a container.
