### ISSUE TITLE
User journey

### ISSUE THREAD

**Issue by bjarneo** [HemmeligOrg/Hemmelig.app#98]
- Super admin
- - Configuration panel for the self hosted version (logo, colors)
- - This includes allowed accounts / i.e. based on email. Block sign in and more (https://github.com/HemmeligOrg/Hemmelig.app/issues/94)
- Diffie-Hellman (https://github.com/HemmeligOrg/Hemmelig.app/issues/69) 
- Organizations
- "Friends" (so you can easily use the DH algorithm)
-

**Comment by luismanson** [comment]
Hello, I saw issue #94 a few days ago and saw you the "user journey" but im not familiar with that concept. Would you consider to allow logins regardless of registration being disabled or add another setting to control this?

**Comment by dada513** [comment]
probably would be best to have an option to create an admin account with env variables, and disable upload for non admins. I don't want random people uploading shit to my server.
Also, LDAP support would be quite useful for me, is that desired? If so, I can get a quick PR going for it

**Comment by bjarneo** [comment]
@luismanson / @dada513 

Yeah, it would be an admin dashboard where you can adjust the settings you would like for your application. That is my thoughts on this as well.

So the admin allows either anyone to register an account. Organizations. Add people manually. Or something in between here.

@dada513 Sure, feel free to create LDAP support. I think more people would have the need of that as well

**Comment by dada513** [comment]
@bjarneo I think for settings it's alright to do it like other services and just have configuration via environment variables, like HEMMLIG_ALLOW_REGISTER, makes deployment easier to be automated. But an admin panel would be useful for creating users though

**Comment by Zulgrib** [comment]
Where would these settings be stored? Plain files? Database? Would it automatically alter default.cjs or production.cjs? Add an additional file? 

Using env variables bloats the systemd service file and may allow unix users on host to view the variable content where a configuration file or store in database is easier to restrict.

**Comment by bjarneo** [comment]
It will be saved to the database whenever that part is ready.

**Comment by bjarneo** [comment]
The database switch using sqlite has now been implemented, much thanks to @d-513. https://github.com/HemmeligOrg/Hemmelig.app/commit/560831d734cf7b06e9de870de916ed88e21e4147

From version 5.0.0 it makes it easier to implement features such as this. Here is a list of tickets that will now be possible:

https://github.com/HemmeligOrg/Hemmelig.app/issues/94
https://github.com/HemmeligOrg/Hemmelig.app/issues/26
https://github.com/HemmeligOrg/Hemmelig.app/issues/168
https://github.com/HemmeligOrg/Hemmelig.app/issues/24

**Comment by bjarneo** [comment]
https://github.com/HemmeligOrg/Hemmelig.app/issues/154
