### ISSUE TITLE
Unhidden password requestpayload

### ISSUE THREAD

**Issue by JJvdg26** [HemmeligOrg/Hemmelig.app#99]
I discoverd after i make a secret message and i set my development tool on in the webbrowser, i can see unhidden in the request payload the password that is created for the secret url.'

The text and Title is well encrypted but not the password that will be used for open the secret link.

Under you see the code in the secret request payload file

 ```
"{text: "OEoqjmmg+HRJLcc4WDT2iGL+jPt5C30C6S9gkAQC1o3PUKDEeuVoLOZrPhg=", files: [],…}
allowedIp
: 
""
files
: 
[]
maxViews
: 
1
password
: 
"Unhidden password in payload attack"
preventBurn
: 
true
text
: 
"OEoqjmmg+HRJLcc4WDT2iGL+jPt5C30C6S9gkAQC1o3PUKDEeuVoLOZrPhg="
title
: 
"EL9r5tcnABDBYnX5cFdzLzHqBtHalRw+DykJ04DzSvn3FypiObtkBRPNTwe7nYVFgsfvsZAmMpVImX5mu4442cSJ26Y="
ttl
: 
300


```

**Comment by JJvdg26** [comment]
I see by the audit request in the comments the same isue that is why close this isue.

**Comment by bjarneo** [comment]
Yeah, well, that is how the Internet works
